### ISSUE TITLE
1.8: Bad Indentation - Lang ES

### ISSUE THREAD

**Issue by reussy** [UltimateGamer200/UltraColor#1]
There is an error in the **messages_es.yml** file

This error came by default and is that there is a period after a quotation mark and that causes an error

It is simple to solve, just removing the point ... So other less experienced users do not have this problem

No need to upload my folder, regards.

**Comment by reussy** [comment]
Update: Line 210 and 396

**Comment by UltimateGamer200** [comment]
Hello!

Thanks for making the report! I have spotted the two periods and have removed them from the default messages_es.yml file. I'll post a new plugin jar on Spigot tomorrow when I get the chance as it's kind of late where I am (you'll also get credit for reporting the bug). Have a good one and thanks again!

- UltimateGamer200

Issue closed.
