### ISSUE TITLE
1.17.1 | Placeholder

### ISSUE THREAD

**Issue by mesl** [UltimateGamer200/UltraColor#11]
Is there a placeholder that returns the player's name including the colors? If not, Could this maybe be added in a future update?

Thank you and kind regards,
Merlyn

**Comment by UltimateGamer200** [comment]
So you mean a placeholder of their display name (that displays the username formatted)? If so, PlaceholderAPI has one for you called, `%player_displayname%`.

**Comment by mesl** [comment]
Thank you! Yes that was the one, It doesn't work on joinmessages (in essentials) but that because something with essentials!

Thank you for your response!
