### ISSUE TITLE
1.17.1: ConsoleError

### ISSUE THREAD

**Issue by mesl** [UltimateGamer200/UltraColor#12]
Seems to only happen onjoin,
![image](https://user-images.githubusercontent.com/10009454/135456678-960b5526-fcaa-4577-913e-193d596224b5.png)
https://pastebin.com/PGmJp3uF

Might have to do with the joinmessage not inluding the colors

Also, Great update! good work!

**Comment by UltimateGamer200** [comment]
Oh, it looks like I forgot to check if the player had no format when trying to apply gradients on player join. That's what this error is telling me. I found and applied a fix on a private GitHub repo for this plugin, but I'm currently at school, so I'll have to add it to a new jar sometime tonight.  Thanks for reporting it!

**Comment by UltimateGamer200** [comment]
Just tested the fix and it works! Will be in the next update!
