### ISSUE TITLE
Feature nicklist/listnicks

### ISSUE THREAD

**Issue by ItzRonaldMLG** [UltimateGamer200/UltraColor#16]
A list with all nicked players maybe like /nicklist local to see the players on the server you are on and /nicklist global to see from the bungee network?
Nick name &c-> Real name
%ucolor_colored_nickname% &c-> &7%ucolor_name_color%%player_name%

PS:
Seems like Interactive chat works with gradient colors atm if you didnt know.
https://i.imgur.com/7gkO1hu.png

**Comment by UltimateGamer200** [comment]
Hello!

After some experimenting with your suggestion, it seems to be working well! You're able to get both nicknames from the current you're on and from all servers that are connected to the database you set up. Should be in the next update!

Also, interesting to hear Interactive Chat now works with gradient colors. I'll get that updated on the main plugin page.

Thanks!
