### ISSUE TITLE
1.16.4: Gradient

### ISSUE THREAD

**Issue by JHiroshige** [UltimateGamer200/UltraColor#2]
So I just got this Plugin but the Gradient Name isnt working. Im using Paper and ChatControlPro for the Chat. I've already tried 3 different Placeholders for the Name. None of them worked. The name remains the same.
![image](https://user-images.githubusercontent.com/67478052/111082070-a20d2300-8506-11eb-9282-a1785986d48a.png)
This is set to false

I dont see any errors? Whats the problem

**Comment by UltimateGamer200** [comment]
Hm, Interesting. I just gave this a go on my 1.16.5 test server and nothing much seems to be wrong. Just make sure of a few things:

- Your server is at least 1.16 (we don't support gradients for servers under 1.16).
- You do indeed have change-displayname for EssentialsX set to false and reload that plugin after changing it (the only reason that message appears is when it's set to true).
-

**Comment by JHiroshige** [comment]
Hey

- The server is on 1.16.4

- I checked change-displayname again and its set to false

- I tried every possible placeholder: {player} {display_name} {nick} {essentials_nickname}

Chat gradient works perfectly fine
Only the name isnt working

**Comment by UltimateGamer200** [comment]
Hm, really strange. On my test server, I also had "Chat_Listener_Priority" set to HIGHEST in UltraColor's settings.yml file and Formatter set to HIGH in ChatControl's settings file. Maybe you can try setting those and then rebooting and seeing if that works!

**Comment by JHiroshige** [comment]
I just did that but no results. Any other ideas?

**Comment by JHiroshige** [comment]
I just realised something

![image](https://user-images.githubusercontent.com/67478052/111363613-8cc40000-8690-11eb-9337-bb4e2903f256.png)

It might be the wrong Placeholder`But Im using the one u told to use: {player}

**Comment by UltimateGamer200** [comment]
Yeah, it's most likely the wrong placeholder. I don't think I recall telling you to use "{player}", but I did recall telling you to use "{display_name}". Maybe you can try using {display_name} again or some other placeholder to display the display name until you see the correct display name is being displayed.

**Comment by JHiroshige** [comment]
Hey,

Its working now! Thanks
Is this plugin compatible with a nickname plugin or is this not possible?

**Comment by UltimateGamer200** [comment]
So you mean can UltraColor color nicknames? If that's the case, then I don't think so. This is because when a player selects a name color, we modify the player's display name and just get the real username. I can maybe try to add integration with some common plugins that have a nickname feature (such as Essentials and CMI), but I can't make guarantees that it'll be possible. 

Btw, you're welcome! Glad to hear it's working!
