### ISSUE TITLE
Purpur 1.16.5 | Name Colors Do No Appear In Chat

### ISSUE THREAD

**Issue by blockswerker** [UltimateGamer200/UltraColor#5]
I know it's impossible to be familiar with every combination of plugins and settings, but I'm hoping you might have some ideas. When I or my players set their name color using `/ucolor snc` the chat window confirms that `name color successfully changed` but names just continue to appear in default white.

Chat color setting set via `/ucolor scc` work and display properly. I'm using EssentialsX, TAB and ChatControl-Red.

**Comment by blockswerker** [comment]
Update: In Essentials config.yml I set `change-displayname: false` and that seemed to have done the trick!

**Comment by UltimateGamer200** [comment]
Yeah, I figured that may be the case. Sorry for late response! Glad that did the trick!
