### ISSUE TITLE
1.17.1: Rainbow colors

### ISSUE THREAD

**Issue by mesl** [UltimateGamer200/UltraColor#9]
Rainbow chat colors only seem to work via GUI, If you have a different chatcolor selected and type the command it doesn't change the color

This only affects chatcolor as far as i'm aware

**Comment by UltimateGamer200** [comment]
Ah, looks like I didn't set it to clear the normal chat color after selecting chat rainbow color via that command. This fix has been made and will be in the next update! Thanks for reporting it!
